version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: ${PG_HOST:-postgres}
            port: ${PG_PORT:-5432}
            database: ${PG_DATABASE}
            user: ${PG_USERNAME}
            password: ${PG_PASSWORD}
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~